import fs from 'fs';
import matter from 'gray-matter';
import path from 'path';

const projectRoot = process.cwd();
const postsDirectory = path.join(projectRoot, '_posts');
const pagesDirectory = path.join(projectRoot, '_pages');
const outputFile = path.join(projectRoot, 'src/generated/content.ts');

const sortBySlug = (left, right) => left.slug.localeCompare(right.slug);

const readPostDirectories = () => {
  if (!fs.existsSync(postsDirectory)) {
    return [];
  }

  return fs
    .readdirSync(postsDirectory)
    .filter((entry) => {
      const fullPath = path.join(postsDirectory, entry);
      return fs.statSync(fullPath).isDirectory();
    })
    .sort();
};

const readPageDirectories = () => {
  if (!fs.existsSync(pagesDirectory)) {
    return [];
  }

  return fs
    .readdirSync(pagesDirectory)
    .filter((entry) => {
      const fullPath = path.join(pagesDirectory, entry);
      return fs.statSync(fullPath).isDirectory();
    })
    .sort();
};

const readMarkdownFile = (fullPath) => {
  const fileContents = fs.readFileSync(fullPath, 'utf8');
  const { data, content } = matter(fileContents);

  return {
    data,
    content,
    rawMarkdown: content.replace(/^(?:\r?\n)+/, ''),
  };
};

const posts = readPostDirectories()
  .map((slug) => {
    const markdownPath = path.join(postsDirectory, slug, 'index.md');
    const { data, content, rawMarkdown } = readMarkdownFile(markdownPath);

    return {
      ...data,
      slug,
      content,
      rawMarkdown,
    };
  })
  .sort(sortBySlug);

const pages = Object.fromEntries(
  readPageDirectories()
    .map((slug) => {
      const markdownPath = path.join(pagesDirectory, slug, 'index.md');
      const { data, content, rawMarkdown } = readMarkdownFile(markdownPath);

      return [
        slug,
        {
          slug,
          data,
          content,
          rawMarkdown,
        },
      ];
    })
    .sort(([left], [right]) => left.localeCompare(right)),
);

const output = `// This file is auto-generated by scripts/generate-content.mjs.
// Do not edit this file directly.

export const generatedPosts = ${JSON.stringify(posts, null, 2)};

export const generatedPages = ${JSON.stringify(pages, null, 2)};
`;

fs.writeFileSync(outputFile, output);